### PR TITLE
Keep Best Recordings

### PR DESCRIPTION
**Pull request by Phaeton**
Commit adds a check that prevents the best existing recording from being deleted. Since it's only one recording per scientific_name, should not add much overhead and adds ability to view later.

### CODE REVIEW

**Comment by mmcc-xx** [comment]
Cool thanks!

**Comment by mmcc-xx** [comment]
I'm gonna go ahead and assume that work as advertised :) I've been having ChatGPT write most of the SQL queries.

**Comment by Phaeton** [comment]
Hah, it tested well on my machine:tm:

**Comment by Phaeton** [comment]
@mmcc-xx When will this make it into the backend image? The last two image updates still contain the prior retrieve records line in `recordingcleanup.py`.

I see ```cursor.execute("SELECT id, filename FROM detections WHERE timestamp < ? AND LENGTH(filename) > 0", (timestamp_limit,))``` 

instead of ```cursor.execute("SELECT id, filename FROM detections WHERE timestamp < ? AND LENGTH(filename) > 0 AND (id, filename) NOT IN (SELECT id, filename FROM (SELECT id, filename, max(confidence) FROM detections WHERE LENGTH(filename)> 0 GROUP BY scientific_name))", (timestamp_limit,))```

I am on Image_ID `372dd2694730` which should be latest.

**Comment by mmcc-xx** [comment]
Huh - I thought I built and pushed with that change...

I think you have an old image, if "Digest" is the same as Image_ID
https://hub.docker.com/repository/docker/mmcc73/birdcage_backend/tags?page=1&ordering=last_updated

**Comment by Phaeton** [comment]
Digest is not the same as Image_ID. I grabbed Image_Id from `docker image ls`. If you run `docker exec -it birdcage_backend cat /app/recordingcleanup.py | grep SELECT`, what do you get?

I get ```cursor.execute("SELECT id, filename FROM detections WHERE timestamp < ? AND LENGTH(filename) > 0", (timestamp_limit,))```

**Comment by mmcc-xx** [comment]
Well that's weird - I would have sworn I had built that in, but apparently not.

If you pull now it should be there.

**Pull request merged**
