### PR TITLE
Html modification

### PR DESCRIPTION
**Pull request by matthew73210**
Added link to repo (follows on from my last PR about HA)

### CODE REVIEW

**Comment by mmcc-xx** [comment]
Hi @matthew73210 - is the only additional change from the other PR the change to base.html?

**Comment by matthew73210** [comment]
Hello,
Yes, all I did was add a link to this repo in the base html. Unfortunately I did the pr over the wrong base.

**Comment by matthew73210** [comment]
Ah just check the PR and i modified the .gitignore. It just ignores the local files when doing a local build

**Comment by matthew73210** [comment]
The easiest option would be to refuse the pr and just do a commit with the link.

**Pull request closed without merging**
